version: '3'
services:

  proxy:
    image: nginx    
    ports:
     - "80:80"
     - "443:443"
    depends_on:
     - odoo
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  odoo:
    image: odoo:10
    depends_on:
     - db
  
  db:
    image: postgres:9.4
    environment:
     - POSTGRES_USER=odoo
     - POSTGRES_PASSWORD=odoo
